name: Siddhesh First Action
on: push
jobs:
  build:
    name: Siddhesh Job Ok
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: process.env.MY_NAME

